name: SWE API PUBLISHER

on:
  push:
    branches: 
      - develop

jobs:
  api_update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout api-docs
      uses: actions/checkout@v2
      with:
        repository: RedRoundRobin/api-docs
        path: api-docs
    - name: Move new api in api-docs repo
      run: mv swe-api/apirest/openapi.yaml api-docs/
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add openapi.yaml
        git commit -m "[BOT] Aggiornata la documentazione API" -a
      working-directory: api-docs
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN_ACTION }}
        branch: master 
        directory: api-docs
        repository: RedRoundRobin/api-docs
    - name: Slack Notification
      uses: homoluctus/slatify@v2.0.1
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'Aggiornamento documentazione API'
        mention: 'here'
        mention_if: 'failure'
        channel: '#devops_software'
        username: 'API generator'
        url: ${{ secrets.SLACK_SW_WEBHOOK }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
