name: SWE API PUBLISHER

on:
  push:
    branches: 
      - develop
      - feature/**
  pull_request:
    branches: 
      - develop
      - feature/**

jobs:
  ci_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Generate API 
      run: mvn clean verify -Dspring.application.admin.enabled=true -Dsonar.login=${{ secrets.SONARCLOUD_LOGIN_KEY }} --file apirest/pom.xml -e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "[BOT] Aggiornata la documentazione API" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}