name: SWE API PUBLISHER

on:
  push:
    branches: 
      - develop
      - feature/**
  pull_request:
    branches: 
      - develop
      - feature/**

jobs:
  api_update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout swe-kafka-db
      uses: actions/checkout@v2
      with:
        repository: RedRoundRobin/swe-kafka-db
        path: swe-kafka-db
        ref: develop
    - name: Start databases
      run: docker-compose -f swe-kafka-db/kafka/docker-compose.yml up -d
    - name: Checkout swe-api
      uses: actions/checkout@v2
      with:
        path: swe-api
        fetch-depth: 0
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Generate API 
      run: mvn clean verify -Dspring.application.admin.enabled=true -Dsonar.login=${{ secrets.SONARCLOUD_LOGIN_KEY }} --file swe-api/apirest/pom.xml -e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Move new api in apirest folder
      run: mv swe-api/apirest/target/openapi.yaml swe-api/apirest/
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "[BOT] Aggiornata la documentazione API" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: feature/testApiDocs